#!/bin/bash
#By yftung, 2017/02/14

supportingTypes=("bash")
result=""

function askFor()
{
    echo $1
    read line
    result=$line
}

function createBash()
{
    fileName=$1
    if [ -f ${fileName} ] ; then
	echo "File already exists! Failed to create."
    elif [ -d ${fileName} ] ; then
	echo "Folder already exists! Failed to create."
    else
	echo "Creating bash template..."
	echo "#!/bin/bash" >> ${fileName}
	echo "" >> ${fileName}
	chmod +x ${fileName}
	echo "Done"
	vi ${fileName}
    fi
}

# main
if [ "$#" -ne 1 ] ; then
    echo "Please specify type. Supporting types are:"
    for types in ${supportingTypes}
    do
	echo " + ${types}"
    done
elif [ "$1" == "bash" ] ; then
    askFor "What is the file name?"
    createBash $result
elif [[ "$1" == *.sh ]] ; then
    createBash $1
else
    echo "Illegal type: $1"
fi

